definitions:
  mdb.Ed713OtqReq:
    properties:
      base_version:
        type: integer
      core_version:
        type: integer
      mac:
        type: string
    type: object
  mysql.Ed713OtaData:
    properties:
      baseFileSize:
        type: integer
      baseOtaUrl:
        type: string
      coreFileSize:
        type: integer
      coreOtaUrl:
        type: string
      mac:
        type: string
      remoteBaseVersion:
        type: integer
      remoteCoreVersion:
        type: integer
      upgrade:
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/device/getED713Ota:
    post:
      description: get ED713 ota version information
      parameters:
      - description: OTA request
        in: body
        name: in
        required: true
        schema:
          $ref: '#/definitions/mdb.Ed713OtqReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mysql.Ed713OtaData'
      summary: getED713Ota
      tags:
      - ED713
swagger: "2.0"
