/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_medialib_jni_MediaJni */

#ifndef _Included_com_medialib_jni_MediaJni
#define _Included_com_medialib_jni_MediaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_medialib_jni_MediaJni
 * Method:    openMediaServer
 * Signature: (Ljava/lang/String;Lcom/medialib/jni/MediaJni/IDecodeListener;)I
 */
JNIEXPORT jint JNICALL Java_com_medialib_jni_MediaJni_openMediaServer
  (JNIEnv *, jobject,  jstring, jobject);

/*
 * Class:     com_medialib_jni_MediaJni
 * Method:    closeMediaServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_medialib_jni_MediaJni_closeMediaServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
