/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_medialib_jni_MediaJni */

#ifndef _Included_com_medialib_jni_MediaJni
#define _Included_com_medialib_jni_MediaJni
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_medialib_jni_MediaJni
 * Method:    setParams
 * Signature: (III;Ljava/lang/string;III)V
 */
JNIEXPORT void JNICALL Java_com_medialib_jni_MediaJni_setParams
        (JNIEnv *, jobject, int use_sdk, int enable_codec, int local_port, jstring url, int w, int h, int chunkSize);

/*
 * Class:     com_medialib_jni_MediaJni
 * Method:    openMediaServer
 * Signature: (Ljava/lang/String;Lcom/medialib/jni/MediaJni/IDecodeListener;)I
 */
JNIEXPORT jint JNICALL Java_com_medialib_jni_MediaJni_openMediaServer
  (JNIEnv *, jobject,  jstring, jobject);

/*
 * Class:     com_medialib_jni_MediaJni
 * Method:    closeMediaServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_medialib_jni_MediaJni_closeMediaServer
  (JNIEnv *, jobject);

/*
 * Class:     com_medialib_jni_MediaJni
 * Method:    testMediaCodec
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
extern "C"
JNIEXPORT void JNICALL
Java_com_medialib_jni_MediaJni_testMediaCodec(JNIEnv *, jobject, jstring , jstring );

extern "C"
JNIEXPORT void JNICALL
Java_com_medialib_jni_MediaJni_putTestMediaFile(JNIEnv *env, jobject thiz, jstring test_file);

extern "C"
JNIEXPORT void JNICALL
Java_com_medialib_jni_MediaJni_stopTestMedia(JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif

